"""Create api_user table

Revision ID: 83f821bd9990
Revises: e3dd3c6b6f1b
Create Date: 2026-02-26 19:38:57.555994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83f821bd9990'
down_revision: Union[str, Sequence[str], None] = 'e3dd3c6b6f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_call_count', sa.Integer(), nullable=False),
    sa.Column('last_api_call_date', sa.Date(), nullable=True),
    sa.Column('daily_api_calls_left', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_user_api_key'), 'api_user', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_user_username'), 'api_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_user_username'), table_name='api_user')
    op.drop_index(op.f('ix_api_user_api_key'), table_name='api_user')
    op.drop_table('api_user')
    # ### end Alembic commands ###
